version: '3'
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    env_file:
      - ./docker/db/.env
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

